# Generated by Django 3.2.9 on 2021-11-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=6)),
                ('empname', models.CharField(max_length=200)),
                ('empskills', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_id', models.CharField(max_length=100)),
                ('name_of_title', models.CharField(max_length=50)),
                ('date_of_call_to_people', models.DateField(auto_now_add=True)),
                ('date_of_assigning_task', models.DateField()),
                ('date_of_submistion', models.DateField(auto_now_add=True)),
                ('assigned_to', models.CharField(default=None, max_length=120)),
                ('downlode_attachement', models.FileField(upload_to='doc/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Issuess', 'Issuess'), ('raised', 'raised'), ('submitted', 'submitted')], max_length=200)),
                ('detail', models.TextField(default=None, max_length=120)),
                ('call_to_people', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webapp.employe')),
            ],
        ),
    ]
