# Generated by Django 3.2.9 on 2021-11-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='date_of_call_to_people',
            field=models.DateField(auto_now=True),
        ),
    ]
