# Generated by Django 3.2.9 on 2021-11-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20211105_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='date_of_assigning_task',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='date_of_call_to_people',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
